name: CD - PRODUCTION
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types: [closed]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install -global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
    
    #if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    #runs-on: ubuntu-latest
    #steps:
    #  - name: Trigger Vercel Production Deploy
    #    run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}"


  
